### ISSUE TITLE
`constant_fold_pass()` panics in `apply_rewrite()`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/hugr#996]
For a moderately complex but fully-foldable DFG, `const_fold_pass()` panics, reporting an invalid port.

Test code to reproduce:

```rust
    #[test]
    fn test_folding_pass() {
        // pseudocode:
        //
        // x0 := 3.0
        // x1 := 4.0
        // x2 := fne(x0, x1); // true
        // x3 := flt(x0, x1); // true
        // x4 := and(x2, x3); // true
        // x5 := -10.0
        // x6 := flt(x0, x5) // false
        // x7 := or(x4, x6) // true
        // output x7
        let mut build =
            DFGBuilder::new(FunctionType::new(type_row![], vec![BOOL_T.into()])).unwrap();
        let x0 = build.add_load_const(Value::extension(ConstF64::new(3.0)));
        let x1 = build.add_load_const(Value::extension(ConstF64::new(4.0)));
        let x2 = build.add_dataflow_op(FloatOps::fne, [x0, x1]).unwrap();
        let x3 = build.add_dataflow_op(FloatOps::flt, [x0, x1]).unwrap();
        let x4 = build
            .add_dataflow_op(
                NaryLogic::And.with_n_inputs(2),
                x2.outputs().chain(x3.outputs()),
            )
            .unwrap();
        let x5 = build.add_load_const(Value::extension(ConstF64::new(-10.0)));
        let x6 = build.add_dataflow_op(FloatOps::flt, [x0, x5]).unwrap();
        let x7 = build
            .add_dataflow_op(
                NaryLogic::Or.with_n_inputs(2),
                x4.outputs().chain(x6.outputs()),
            )
            .unwrap();
        let reg = ExtensionRegistry::try_new([
            PRELUDE.to_owned(),
            logic::EXTENSION.to_owned(),
            arithmetic::float_types::EXTENSION.to_owned(),
        ])
        .unwrap();
        let mut h = build.finish_hugr_with_outputs(x7.outputs(), &reg).unwrap();
        constant_fold_pass(&mut h, &reg);
        let expected = Value::true_val();
        assert_fully_folded(&h, &expected);
    }
```

Output with `RUST_BACKTRACE=1`:

```
failures:

---- algorithm::const_fold::test::test_folding_pass stdout ----
thread 'algorithm::const_fold::test::test_folding_pass' panicked at hugr/src/hugr/hugrmut.rs:301:9:
Received an invalid port Port(Incoming, 0) for node Node(15) while mutating a HUGR:

 graph LR
    subgraph 0 ["(0) DFG"]
        direction LR
        1["(1) Input"]
        2["(2) Output"]
        6["(6) LoadConstant"]
        5["(5) const:sum:{tag:1, vals:[]}"]
        5--"0:0<br>[]+[]"-->6
        13["(13) LoadConstant"]
        13--"0:0<br>[]+[]"-->2
        12["(12) const:sum:{tag:0, vals:[]}"]
        12--"0:0<br>[]+[]"-->13
        18["(18) LoadConstant"]
        18--"0:1<br>[]+[]"-->11
        7["(7) const:sum:{tag:1, vals:[]}"]
        7--"0:0<br>[]+[]"-->18
        17["(17) LoadConstant"]
        17--"0:0<br>[]+[]"-->11
        16["(16) const:sum:{tag:1, vals:[]}"]
        16--"0:0<br>[]+[]"-->17
        11["(11) logic.And"]
    end

stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: hugr::hugr::hugrmut::panic_invalid_port
             at ./src/hugr/hugrmut.rs:497:9
   3: <T as hugr::hugr::hugrmut::HugrMut>::disconnect
             at ./src/hugr/hugrmut.rs:301:9
   4: <hugr::hugr::rewrite::simple_replace::SimpleReplacement as hugr::hugr::rewrite::Rewrite>::apply
             at ./src/hugr/rewrite/simple_replace.rs:139:17
   5: hugr::hugr::hugrmut::HugrMut::apply_rewrite
             at ./src/hugr/hugrmut.rs:220:9
   6: hugr::algorithm::const_fold::constant_fold_pass
             at ./src/algorithm/const_fold.rs:196:13
   7: hugr::algorithm::const_fold::test::test_folding_pass
             at ./src/algorithm/const_fold.rs:405:9
   8: hugr::algorithm::const_fold::test::test_folding_pass::{{closure}}
             at ./src/algorithm/const_fold.rs:366:27
   9: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
```

**Comment by cqc-alec** [comment]
Mermaid graph shown in error message:
```mermaid
 graph LR
    subgraph 0 ["(0) DFG"]
        direction LR
        1["(1) Input"]
        2["(2) Output"]
        6["(6) LoadConstant"]
        5["(5) const:sum:{tag:1, vals:[]}"]
        5--"0:0<br>[]+[]"-->6
        13["(13) LoadConstant"]
        13--"0:0<br>[]+[]"-->2
        12["(12) const:sum:{tag:0, vals:[]}"]
        12--"0:0<br>[]+[]"-->13
        18["(18) LoadConstant"]
        18--"0:1<br>[]+[]"-->11
        7["(7) const:sum:{tag:1, vals:[]}"]
        7--"0:0<br>[]+[]"-->18
        17["(17) LoadConstant"]
        17--"0:0<br>[]+[]"-->11
        16["(16) const:sum:{tag:1, vals:[]}"]
        16--"0:0<br>[]+[]"-->17
        11["(11) logic.And"]
    end
```

**Comment by Cobord** [comment]
with the rewrites being the find_consts on the first iteration, if let _ = rewrites.drain(3..), then there is no panic, but with 4 there is. For which SimpleReplacement is being used in h.apply_rewrite when the panic occurs. See own-dev where messing with it (replace Value with Const bc didn't pull in "bring back Value").
